version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: rangelbarroso
      WORDPRESS_DB_PASSWORD: elvergudo
      WORDPRESS_DB_NAME: cookies
    volumes:
      - ~/cookies_online/html:/var/www/html:rw

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: cookies
      MYSQL_USER: rangelbarroso
      MYSQL_PASSWORD: elvergudo
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ~/cookies_online/mysql:/var/lib/mysql:rw

# volumes:
#   wordpress:
#   db: 
